python data_process.py --env_id 21 --robo_task full 
#python data_process.py --env_id 22 --robo_task reach
#python data_process.py --env_id 22 --robo_task full 
#python data_process.py --env_id 23 --robo_task reach
#python data_process.py --env_id 23 --robo_task full 
#python data_process.py --env_id 24 --robo_task reach
#python data_process.py --env_id 24 --robo_task full 
#python data_process.py --env_id 25 --robo_task reach
#python data_process.py --env_id 25 --robo_task full 
#python data_process.py --env_id 26 --robo_task reach
#python data_process.py --env_id 26 --robo_task full 
#python data_process.py --env_id 27 --robo_task reach
#python data_process.py --env_id 27 --robo_task full 
#python data_process.py --env_id 28 --robo_task reach
#python data_process.py --env_id 28 --robo_task full 
